### ISSUE TITLE
[IL] Get person declaration

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ops.api#3]
Implement the subj. service according to the [spec](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/persons/get-person-declaration)
Basic [logic](https://edenlab.atlassian.net/wiki/display/EH/IL.Get+person+declaration)

**Comment by lymychp** [comment]
all the tickets should be in [main repo](https://github.com/edenlabllc/ehealth.api/)
